main: gay.gaycraft.plugin.Gaycraft
api-version: 1.19
name: Gaycraft
description: Gaycraft handler plugin
version: 0.1.0
author: Lolas_Pocket_PC
commands:
  color:
    description: "Set the color of your name"
  pronouns:
    description: "Set your pronouns"
  nick:
    description: "Set player nickname"
  rank:
    description: "Set player rank"
  unmute:
    description: "Unmute a player"
  unban:
    description: "Unban a player"
  ban:
    description: "Ban a player"
  kick:
    description: "Kick a player"
  tempban:
    description: "Temporarily ban a player"
  mute:
    description: "Mute a player"
  tempmute:
    description: "Temporarily mute a player"